[package]
name = "brother-ql-rs"
version = "0.1.0"
authors = ["Ryan Petschek <petschekr@gmail.com>"]
edition = "2018"

[dependencies]
rusttype = "0.7.5"
image = "0.21.0"
libusb = "0.3"

[replace]
"libusb-sys:0.2.3"= { git = "https://github.com/cmsd2/libusb-sys/" }
